// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPlayer.Services.Persistence;

#nullable disable

namespace MusicPlayer.Services.Persistence.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20260908102742_PersistPlaybackSession")]
    partial class PersistPlaybackSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MusicPlayer.Services.Persistence.StorageState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("StorageStates");
                });

            modelBuilder.Entity("MusicPlayer.Services.Persistence.StoredPlaybackSession", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CurrentTrackId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PositionTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTrackId");

                    b.ToTable("PlaybackSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlaybackSessions_Id", "Id = 1");

                            t.HasCheckConstraint("CK_PlaybackSessions_Position", "PositionTicks >= 0");
                        });
                });

            modelBuilder.Entity("MusicPlayer.Services.Persistence.StoredPlaylist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("MusicPlayer.Services.Persistence.StoredPlaylistEntry", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaylistId", "Position");

                    b.HasIndex("TrackId");

                    b.ToTable("PlaylistEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlaylistEntries_Position", "Position >= 0");
                        });
                });

            modelBuilder.Entity("MusicPlayer.Services.Persistence.StoredQueueEntry", b =>
                {
                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Position");

                    b.HasIndex("TrackId");

                    b.ToTable("QueueEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_QueueEntries_Position", "Position >= 0");
                        });
                });

            modelBuilder.Entity("MusicPlayer.Services.Persistence.StoredTrack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PathKey")
                        .IsUnique();

                    b.HasIndex("Artist", "Album");

                    b.ToTable("Tracks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tracks_Duration", "DurationTicks >= 0");
                        });
                });

            modelBuilder.Entity("MusicPlayer.Services.Persistence.StoredPlaybackSession", b =>
                {
                    b.HasOne("MusicPlayer.Services.Persistence.StoredTrack", "CurrentTrack")
                        .WithMany()
                        .HasForeignKey("CurrentTrackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentTrack");
                });

            modelBuilder.Entity("MusicPlayer.Services.Persistence.StoredPlaylistEntry", b =>
                {
                    b.HasOne("MusicPlayer.Services.Persistence.StoredPlaylist", null)
                        .WithMany("Entries")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicPlayer.Services.Persistence.StoredTrack", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicPlayer.Services.Persistence.StoredQueueEntry", b =>
                {
                    b.HasOne("MusicPlayer.Services.Persistence.StoredTrack", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicPlayer.Services.Persistence.StoredPlaylist", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
